[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = [
    "-C", "target-cpu=native",
    "--cfg", "tracing_unstable"
]

[target.aarch64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = [
    "-C", "target-cpu=native",
    "--cfg", "tracing_unstable"
]

[target.x86_64-apple-darwin]
rustflags = [
    "-C", "target-cpu=native",
    "-C", "split-debuginfo=unpacked",
    "--cfg", "tracing_unstable"
]

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "target-cpu=native",
    "-C", "split-debuginfo=unpacked",
    "--cfg", "tracing_unstable"
]
